spring:
  application:
    name: QUEUE-was

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:default}
    username: ${DATABASE_USERNAME:default}
    password: ${DATABASE_PASSWORD:default}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  data:
   redis:
     host: ${REDIS_HOST:default}
     port: ${REDIS_PORT:6379}
     ssl:
       enabled: true

  profiles:
    active: dev


jwt:
  token:
    access:
      expire-time: ${JWT_ACCESS_EXPIRE_TIME:7200000}
      secret-key: ${JWT_ACCESS_SECRET_KEY:thisisexamplesecretkeyforaccesstokenthisisexamplesecretkeyforaccesstokenthisisexamplesecretkey}
springdoc:
  swagger-ui:
    persistAuthorization: true

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.queuewas: debug
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    async:
      request-timeout: -1

logging:
  level:
    com.queuewas: info
    org.hibernate.sql: info
    # org.hibernate.orm.jdbc.bind: off
    com.zaxxer.hikari.HikariConfig: debug
    # com.zaxxer.hikari: trace
