package com.queuewas.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ReasonCode {

	/**
	 * 400 BAD request
	 */
	INVALID_REQUEST_SYNTAX(0),
	MISSING_REQUIRED_PARAMETER(1),
	MALFORMED_PARAMETER(2),
	MALFORMED_REQUEST_BODY(3),
	INVALID_REQUEST(4),
	CLIENT_ERROR(5),

	/**
	 * 401 UNAUTHORIZED
	 */
	MISSING_OR_INVALID_AUTHENTICATION_CREDENTIALS(0),
	EXPIRED_OR_REVOKED_AUTHENTICATION_TOKEN(1),
	INSUFFICIENT_PERMISSIONS(2),
	TAMPERED_TOKEN(3),
	WITHOUT_OWNERSHIP(4),
	MALFORMED_TOKEN(5),

	/**
	 * 403 FORBIDDEN
	 */
	ACCESS_TO_THE_RESOURCE_IS_FORBIDDEN(0),
	IP_ADDRESS_BLOCKED(1),
	USER_ACCOUNT_BANNED(2),

	/**
	 * 404 NOT FOUND
	 */
	REQUESTED_RESOURCE_NOT_FOUND(0),
	INVALID_URL_OR_ENDPOINT(1),

	/**
	 * 405 METHOD NOT ALLOWED
	 */
	REQUEST_METHOD_NOT_SUPPORTED(0),

	/**
	 * 406 NOT ACCEPTABLE
	 */
	REQUESTED_RESOURCE_FORMAT_NOT_SUPPORTED(0),

	/**
	 * 409 CONFLICT
	 */
	REQUEST_CONFLICT_WITH_CURRENT_STATE_OF_RESOURCE(0),
	RESOURCE_ALREADY_EXISTS(1),

	/**
	 * 422 UNPROCESSABLE ENTITY
	 */
	REQUIRED_PARAMETER_MISSING_IN_REQUEST_BODY(0),
	VALIDATION_ERRORS_IN_REQUEST_DATA(1),
	TYPE_MISMATCH_ERROR_IN_REQUEST_BODY(2),

	/**
	 * 500 INTERNAL SERVER ERROR
	 */
	UNEXPECTED_ERROR(0);

	private final int code;
}
